project:
  type: website
  output-dir: ../docs

website:
  title: "Antara Sudhir"
  site-url: "https://antarasu.github.io"
  favicon: ""
  
  navbar:
    background: dark
    foreground: light
    search: false
    left:
      - href: index.qmd
        text: Home
      - href: experience.qmd
        text: Experience
      - href: projects.qmd
        text: Projects
      - href: credentials.qmd
        text: Credentials & Skills
      - href: files/Resume_Antara_Sudhir.pdf
        text: Resume
    right:
      - icon: github
        href: https://github.com/sudhir-antara
      - icon: linkedin
        href: https://www.linkedin.com/in/antarasudhir
      - icon: envelope
        href: mailto:antara.sudhir@gmail.com

format:
  html:
    theme: none
    css: styles.css
    toc: false
